name: painn
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - ipython=8.27.0=py312h06a4308_0
  - jedi=0.19.1=py312h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - python=3.12.3=h996f2a0_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - traitlets=5.14.3=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - idna==3.10
      - jinja2==3.1.4
      - lightning==2.4.0
      - lightning-utilities==0.11.8
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.1
      - propcache==0.2.0
      - psutil==6.1.0
      - pyparsing==3.2.0
      - pytorch-lightning==2.4.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - sympy==1.13.1
      - torch==2.5.1
      - torch-geometric==2.6.1
      - torchmetrics==1.5.1
      - tqdm==4.66.6
      - triton==3.1.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - yarl==1.17.1